// Code generated by MockGen. DO NOT EDIT.
// Source: lib/web/web.go

// Package web is a generated GoMock package.
package web

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	prchecklist "github.com/motemen/prchecklist"
	url "net/url"
	reflect "reflect"
)

// MockGitHubGateway is a mock of GitHubGateway interface
type MockGitHubGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubGatewayMockRecorder
}

// MockGitHubGatewayMockRecorder is the mock recorder for MockGitHubGateway
type MockGitHubGatewayMockRecorder struct {
	mock *MockGitHubGateway
}

// NewMockGitHubGateway creates a new mock instance
func NewMockGitHubGateway(ctrl *gomock.Controller) *MockGitHubGateway {
	mock := &MockGitHubGateway{ctrl: ctrl}
	mock.recorder = &MockGitHubGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGitHubGateway) EXPECT() *MockGitHubGatewayMockRecorder {
	return m.recorder
}

// AuthCodeURL mocks base method
func (m *MockGitHubGateway) AuthCodeURL(state string, redirectURI *url.URL) string {
	ret := m.ctrl.Call(m, "AuthCodeURL", state, redirectURI)
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthCodeURL indicates an expected call of AuthCodeURL
func (mr *MockGitHubGatewayMockRecorder) AuthCodeURL(state, redirectURI interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCodeURL", reflect.TypeOf((*MockGitHubGateway)(nil).AuthCodeURL), state, redirectURI)
}

// AuthenticateUser mocks base method
func (m *MockGitHubGateway) AuthenticateUser(ctx context.Context, code string) (*prchecklist.GitHubUser, error) {
	ret := m.ctrl.Call(m, "AuthenticateUser", ctx, code)
	ret0, _ := ret[0].(*prchecklist.GitHubUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateUser indicates an expected call of AuthenticateUser
func (mr *MockGitHubGatewayMockRecorder) AuthenticateUser(ctx, code interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateUser", reflect.TypeOf((*MockGitHubGateway)(nil).AuthenticateUser), ctx, code)
}
