// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/motemen/prchecklist/v2/lib/web (interfaces: GitHubGateway)

// Package web is a generated GoMock package.
package web

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	prchecklist "github.com/motemen/prchecklist/v2"
	url "net/url"
	reflect "reflect"
)

// MockGitHubGateway is a mock of GitHubGateway interface
type MockGitHubGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubGatewayMockRecorder
}

// MockGitHubGatewayMockRecorder is the mock recorder for MockGitHubGateway
type MockGitHubGatewayMockRecorder struct {
	mock *MockGitHubGateway
}

// NewMockGitHubGateway creates a new mock instance
func NewMockGitHubGateway(ctrl *gomock.Controller) *MockGitHubGateway {
	mock := &MockGitHubGateway{ctrl: ctrl}
	mock.recorder = &MockGitHubGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGitHubGateway) EXPECT() *MockGitHubGatewayMockRecorder {
	return m.recorder
}

// AuthCodeURL mocks base method
func (m *MockGitHubGateway) AuthCodeURL(arg0 string, arg1 *url.URL) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthCodeURL", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthCodeURL indicates an expected call of AuthCodeURL
func (mr *MockGitHubGatewayMockRecorder) AuthCodeURL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCodeURL", reflect.TypeOf((*MockGitHubGateway)(nil).AuthCodeURL), arg0, arg1)
}

// AuthenticateUser mocks base method
func (m *MockGitHubGateway) AuthenticateUser(arg0 context.Context, arg1 string) (*prchecklist.GitHubUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateUser", arg0, arg1)
	ret0, _ := ret[0].(*prchecklist.GitHubUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateUser indicates an expected call of AuthenticateUser
func (mr *MockGitHubGatewayMockRecorder) AuthenticateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateUser", reflect.TypeOf((*MockGitHubGateway)(nil).AuthenticateUser), arg0, arg1)
}
